// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjhJlOxbB6Hlk6_ppvLKGvgRt_0DwK814',
    appId: '1:424354269282:web:9c5f35defa4a9e872ee93b',
    messagingSenderId: '424354269282',
    projectId: 'car-workshop-app',
    authDomain: 'car-workshop-app.firebaseapp.com',
    storageBucket: 'car-workshop-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz4UUcqDlIDBaTANFRn44gTWGTxKS6RI4',
    appId: '1:424354269282:android:805d3b6cf34f92282ee93b',
    messagingSenderId: '424354269282',
    projectId: 'car-workshop-app',
    storageBucket: 'car-workshop-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Y7Rk2Mq7N_vXKgOjcKnGaBTrII6DldE',
    appId: '1:424354269282:ios:1e6c06df2488b1b52ee93b',
    messagingSenderId: '424354269282',
    projectId: 'car-workshop-app',
    storageBucket: 'car-workshop-app.appspot.com',
    iosBundleId: 'com.example.carWorkshopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Y7Rk2Mq7N_vXKgOjcKnGaBTrII6DldE',
    appId: '1:424354269282:ios:1e6c06df2488b1b52ee93b',
    messagingSenderId: '424354269282',
    projectId: 'car-workshop-app',
    storageBucket: 'car-workshop-app.appspot.com',
    iosBundleId: 'com.example.carWorkshopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjhJlOxbB6Hlk6_ppvLKGvgRt_0DwK814',
    appId: '1:424354269282:web:48205d826a96e6732ee93b',
    messagingSenderId: '424354269282',
    projectId: 'car-workshop-app',
    authDomain: 'car-workshop-app.firebaseapp.com',
    storageBucket: 'car-workshop-app.appspot.com',
  );
}
